<% if @object.try(:errors).try(:any?) %> <!--.try makes sure that you don't have a nil in there that's going to throw an error as you chain methods. It will skip doin -->
 <div id="error_explanation">
   <h2>
     <%= pluralize(@object.errors.count, "error") %>
     prohibited this from being saved:
   </h2>
 
   <ul>
   <% @oject.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>